<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['home_reports_app_description'] = 'Драйвер Домашний отчет разработан для домашних сред.';
$lang['home_reports_app_name'] = 'Домашний отчет';
$lang['home_reports_banner'] = 'Добро пожаловать в Домашний отчет! Такие доклады предназначены, чтобы быть полезным в домашних условиях.';
$lang['home_reports_home_reports'] = 'Домашний отчет';
