<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['home_reports_app_description'] = 'Sterownik raportów domowych zaprojektowany jest do środowisk domowych.';
$lang['home_reports_app_name'] = 'Raporty domowe';
$lang['home_reports_banner'] = 'Witamy w raportach domowych!  Raporty te zostały zaprojektowane tak aby były przydatne w środowisku domowym.';
$lang['home_reports_home_reports'] = 'Raporty domowe';
